# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2c56d9d06f6cf70d70b8635f533c336d50d055613736e97aa6b653a002a31f55ae6fc3dc8d6e1066ae7d757f2ad80b148f5f00a05ad03c2a3951966cf846f5b

test:
  secret_key_base: cc39da677fd16831554f178c14afff3cac3574ddd15502d4a5243b6b9ff24a016e0adcec39055ec9098f202fbf8525f392a53a96e9ab9dae5215920296831fbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
